# Lecture 1: Numpy Arrays

## Array Basics

In [2]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])

In [2]:
arr

array([1, 2, 3])

In [3]:
# Python list vs Numpy matrix
my_mat = ([1, 2, 3], [4, 5, 6], [7, 8, 9])
my_mat

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [4]:
# NB the two sets of brackets indicate
# a 2D array, or matrix
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Like the python range function
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# Also useful
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
# To produce random numbers (0-1):
np.random.rand(2,2)

array([[ 0.9078085 ,  0.35062646],
       [ 0.57754045,  0.01946507]])

In [16]:
# To produce random integers:
# NB low is inclusive, high is exclusive
np.random.randint(1, 100, (2,2))

array([[37, 90],
       [20, 34]])

## Useful Array Methods

In [18]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
ranarr = np.random.randint(0,50,10)

In [13]:
ranarr

array([23, 46, 47, 19, 47, 11, 32,  7, 16, 42])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
print(f'Ranarr Max Value: {ranarr.max()}')
print(f'Ranarr Max index: {ranarr.argmax()}')

Ranarr Max Value: 47
Ranarr Max index: 2


In [20]:
ranarr.min()

7

In [23]:
arr.shape

(25,)

In [24]:
arr = arr.reshape(5,5)

In [25]:
arr.shape

(5, 5)

In [26]:
arr.dtype

dtype('int64')

In [28]:
# A quick tip, you can import any function
# if it will be used frequently in code
from numpy.random import randint

In [30]:
randint(2,10)

7

# Lecture 2: Numpy Array Indexing


## Array Indexing


In [6]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Use standard index slicing syntax
arr[8]

8

In [8]:
# Or for a range of values
arr[1:5]

array([1, 2, 3, 4])

In [9]:
# Remember it is 0 indexed
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
# to start at the beginning
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
#To go to the end
# NB This actually says everything beyond index 4, idx 4 = 3, so it starts at 4
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
# To start at the end
arr[-5:-3]

array([6, 7])

## Array Broadcasting & Referencing

In [23]:
# Watch this....array referencing
slice_of_array = arr[0:5]

In [24]:
slice_of_array

array([0, 1, 2, 3, 4])

In [25]:
slice_of_array[:] = 100

In [26]:
slice_of_array

array([100, 100, 100, 100, 100])

Boom! It also changes the value of the original array!!!
Be very careful with this. Numpy does this on purpose to avoid memory issues
It creates references to the data so that you can work on it, without duplicating.

In [27]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

To create a copy, you need to explicitly request a copy, as follows:

In [28]:
arr_copy = arr[0:5].copy()

In [29]:
arr_copy

array([100, 100, 100, 100, 100])

In [30]:
arr_copy[:] = 45

In [33]:
# See, different
print(arr_copy)
print(arr)

[45 45 45 45 45]
[100 100 100 100 100   5   6   7   8   9  10]


## 2D Arrays

In [36]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
# Double bracket method
print(arr_2d[0])
print(arr_2d[0][0])
print(arr_2d[1][2])

[ 5 10 15]
5
30


In [42]:
# Comma Method --- RECOMMENDED
print(arr_2d[0])
print(arr_2d[0,0])
print(arr_2d[1,2])

[ 5 10 15]
5
30


In [93]:
# Index slicing can be used to grab sub sections of the array
print(arr_2d[1:,1:])

[[25 30]
 [40 45]]


In [95]:
# This is a little confusing, but to do this with the double brackets
# you must get row idx 1 onwards [1:] and then get all rows and col idx 1 onwards [:,1:]
arr_2d[1:][:,1:]

array([[25, 30],
       [40, 45]])

In [98]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

## Conditional Array Selection

In [99]:
arr = np.arange(1,11)

In [100]:
# Applying a condition will return an array of True/False
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [102]:
# This can then be used to grab sections of the original array
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [104]:
# Or...
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [105]:
arr2d = np.arange(50).reshape(5,10)

In [106]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Lecture 3: Numpy Operations

## Simple Array Calcs

In [118]:
arr = np.arange(0,11)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
# Simple operations are as expected
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [121]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [122]:
# NOTE however that in normal python division by 0 throws an error
# but with numpy, it will give a warning and return a value
1/0

ZeroDivisionError: division by zero

In [123]:
arr / arr

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [124]:
1 / arr

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

## More Complex Math Functions

In [125]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [126]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [127]:
np.max(arr)

10

In [128]:
arr.max()

10

In [129]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [133]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [136]:
np.arctan(arr)

array([ 0.        ,  0.78539816,  1.10714872,  1.24904577,  1.32581766,
        1.37340077,  1.40564765,  1.42889927,  1.44644133,  1.46013911,
        1.47112767])

More functions can be found here [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)